# -*- coding: utf-8 -*-
"""01_audio_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kl52OR1JHJrD1FbLznypukTSm5BZZTDY
"""

from google.colab import drive
drive.mount('/content/drive')

!apt-get install ffmpeg -y
!pip install pydub librosa tqdm

import os

raw_path = "/content/drive/MyDrive/EmergencyCallProject/dataset/raw_audio"
processed_path = "/content/drive/MyDrive/EmergencyCallProject/dataset/processed_audio"

os.makedirs(processed_path, exist_ok=True)

from pydub import AudioSegment
from tqdm import tqdm

files = os.listdir(raw_path)

for file in tqdm(files[:10]):  # first 10 files
    if file.endswith(".mp3"):

        mp3_path = os.path.join(raw_path, file)
        wav_path = os.path.join(processed_path, file.replace(".mp3", ".wav"))

        audio = AudioSegment.from_file(mp3_path)

        # Convert to mono + 16kHz
        audio = audio.set_channels(1)
        audio = audio.set_frame_rate(16000)

        audio.export(wav_path, format="wav")

os.listdir(processed_path)[:5]

from IPython.display import Audio

Audio(processed_path + "/" + os.listdir(processed_path)[0])

import librosa

file_path = processed_path + "/" + os.listdir(processed_path)[0]

audio, sr = librosa.load(file_path, sr=None)

print("Sample rate:", sr)
print("Duration:", len(audio)/sr)

for file in tqdm(files):
    if file.endswith(".mp3"):
        mp3_path = os.path.join(raw_path, file)
        wav_path = os.path.join(processed_path, file.replace(".mp3", ".wav"))

        try:
            audio = AudioSegment.from_file(mp3_path)
            audio = audio.set_channels(1)
            audio = audio.set_frame_rate(16000)
            audio.export(wav_path, format="wav")
        except Exception as e:
            print(f"Error processing {file}: {e}")