# -*- coding: utf-8 -*-
"""02_speech_to_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hs1RQp3UYU2ziT7PXhMDG7QMRqk8uuGh
"""

import torch
print(torch.cuda.is_available())

!pip install openai-whisper
!pip install torch

from google.colab import drive
drive.mount('/content/drive')

import os

processed_path = "/content/drive/MyDrive/EmergencyCallProject/dataset/processed_audio"
transcript_path = "/content/drive/MyDrive/EmergencyCallProject/dataset/transcripts"

os.makedirs(transcript_path, exist_ok=True)

import whisper

model = whisper.load_model("base")

import os
from tqdm import tqdm

files = os.listdir(processed_path)

for file in tqdm(files[:5]):

    if file.endswith(".wav"):

        file_path = os.path.join(processed_path, file)

        result = model.transcribe(file_path)

        text = result["text"]

        txt_file = file.replace(".wav", ".txt")

        with open(os.path.join(transcript_path, txt_file), "w") as f:
            f.write(text)

os.listdir(transcript_path)[:5]

with open(os.path.join(transcript_path, os.listdir(transcript_path)[0])) as f:
    print(f.read())

with open(os.path.join(transcript_path, os.listdir(transcript_path)[1])) as f:
    print(f.read())

files = sorted(os.listdir(processed_path))
print("Total files:", len(files))

batch1 = files[:350]
batch2 = files[350:]

import os
from tqdm import tqdm

files = os.listdir(processed_path)

for file in tqdm(batch1):

    if file.endswith(".wav"):

        txt_file = file.replace(".wav", ".txt")
        txt_path = os.path.join(transcript_path, txt_file)

        # skip if already done
        if os.path.exists(txt_path):
            continue

        file_path = os.path.join(processed_path, file)

        result = model.transcribe(file_path)

        with open(txt_path, "w") as f:
            f.write(result["text"])

import os
from tqdm import tqdm

files = os.listdir(processed_path)

for file in tqdm(batch2):

    if file.endswith(".wav"):

        txt_file = file.replace(".wav", ".txt")
        txt_path = os.path.join(transcript_path, txt_file)

        if os.path.exists(txt_path):
            continue

        file_path = os.path.join(processed_path, file)

        result = model.transcribe(file_path)

        with open(txt_path, "w") as f:
            f.write(result["text"])

import os
import pandas as pd

data = []

for file in os.listdir(transcript_path):

    if file.endswith(".txt"):

        with open(os.path.join(transcript_path, file)) as f:
            text = f.read()

        data.append([file, text])

df = pd.DataFrame(data, columns=["file", "transcript"])

df.head()

df.to_csv("/content/drive/MyDrive/EmergencyCallProject/dataset/transcripts.csv", index=False)