# -*- coding: utf-8 -*-
"""Copy of 03_text_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S9RtKUr3oVb3TyRUFGRk3dAN-kgzAsXd
"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/EmergencyCallProject/dataset/final_dataset.csv")

df = df.dropna()

df["transcript"] = df["transcript"].str.lower().str.strip()

df = df[df["transcript"] != ""]

df = df[df["transcript"].str.len() > 5]

df["label"] = df["label"].str.lower().str.strip()

df = df.reset_index(drop=True)

df.head()

df.to_csv("/content/drive/MyDrive/EmergencyCallProject/dataset/final_dataset.csv", index=False)